/*
 * @Author: zhanghao
 * @Date: 2023-06-05 17:14:31
 * @LastEditors: zhanghao
 * @LastEditTime: 2023-07-21 18:02:48
 * @Description: 
 * @FilePath: \dcus\sidebars.js
 */
/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{ type: 'autogenerated', dirName: 'intro' }],
  threejs: [
    {
      type: 'category',
      label: 'threejs',
      link: {
        type: 'doc',
        id: 'category/threejs'
      },

      items: [{ type: 'autogenerated', dirName: 'threejs' }],
    }
    // { type: 'autogenerated',dirName:'threejs' }
  ],
  docusaurus: [{ type: 'autogenerated', dirName: 'docusaurus' }]
  // But you can create a sidebar manually

  // tutorialSidebar: [
  //   {
  //     type: 'category',
  //     label: 'Tutorial',
  //     items: ['tutorial-basics/create-a-document'],
  //   },
  // ],

};

module.exports = sidebars;
